spring.profiles.active=dev

info.app.name=Mini Project - Employee Management System
info.app.version=1.0.0
info.app.description=Employee Management System

logging.level.org.springframework.boot.context.config=INFO
spring.application.name=employee-management
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n%ex

spring.cache.caffeine.spec=maximumSize=10,expireAfterAccess=1m
